### PR TITLE
Js partials2

### PR DESCRIPTION
**Pull request by katherinebl**
Second try for partials:

Hi girls, I create this branch to split the main js file and create partials.
The partials are called from config.json.
If you have any question please contact me... Thanks! :)

### CODE REVIEW

**Comment by katherinebl** [comment]
Thank you guys for reviewing this! 

I'll make the requested changes right now and send a new PR. Thanks again for your time invested in the reviews.

**Comment by katherinebl** [comment]
Hi girls! I resolved all the problems with repeated declarations that were bugging the js. I tested with the console open and it works fine, although I think maybe we should wait till the end to merge this branch with dev, because there must be new js code since I create this branch... What do you guys think? 

In any case, the branch is working now and we just have to wait until everyone is ready to merge with dev ;) 

Thank you!

**Comment by natalia-pn** [comment]
Hi, Katherine! Good work! Waiting for you to merge dev into this branch to see if everything works fine.

**Comment by renrith** [comment]
Works perfectly with the changes! Great job girls!

**Pull request merged**
